apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
  annotations:
    {{- include "nginx-app.annotations" . | nindent 4 }}
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen {{ .Values.service.port }};

            location / {
                auth_basic "Restricted";
                auth_basic_user_file /etc/nginx/auth/.htpasswd;
                root /usr/share/nginx/html;
                index index.html;
            }

            location /health {
                auth_basic off;
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }
    }