name: "ECS Terraform: Apply & Docker"

on:
  workflow_dispatch:

concurrency:
  group: terraform-ecs-apply
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  apply:
    uses: SebastianCielma/shared-actions/.github/workflows/ecs-part3-deploy.yml@main
    with:
      aws_region: "eu-north-1"
      working_dir: "ECS app (Part 3)"
      project_name: "part3"
      plan_workflow_name: "ecs_plan.yml"
    secrets:
      APPLY_ROLE_ARN: ${{ secrets.AWS_APPLY_ROLE_ARN }}
      ECR_REPOSITORY_URL: ${{ secrets.AWS_ECR_URL }}