name: "ECS Terraform: Apply & Docker"

on:
  workflow_dispatch:

concurrency:
  group: terraform-ecs
  cancel-in-progress: false

env:
  AWS_REGION: "eu-north-1"
  WORKING_DIR: "ECS app (Part 3)"
  TF_VAR_project_name: "part3"
  APPLY_ROLE_ARN: ${{ secrets.AWS_APPLY_ROLE_ARN }}
  ECR_REPOSITORY_URL: ${{ secrets.AWS_ECR_URL }}

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  apply-and-docker:
    name: Build Docker & Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ecs_plan.yml
          name: tfplan
          path: ${{ env.WORKING_DIR }}

      - name: Configure AWS Credentials (Apply Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.APPLY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_URL }}:latest .
          docker push ${{ env.ECR_REPOSITORY_URL }}:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
