name: "ECS Terraform: Init & Plan"

on:
  push:
    branches:
      - main
    paths:
      - 'ECS app (Part 3)/**' 

concurrency:
  group: terraform-ecs-plan
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    uses: SebastianCielma/shared-actions/.github/workflows/ecs-part3-plan.yml@main
    with:
      aws_region: "eu-north-1"
      working_dir: "ECS app (Part 3)"
      project_name: "part3"
    secrets:
      PLAN_ROLE_ARN: ${{ secrets.AWS_PLAN_ROLE_ARN }}